/**
 * Derives every favicon asset from the two hand-authored source SVGs
 * (public/icon-gy.svg, public/icon-wp.svg). Run after editing either one:
 *
 *   bun run scripts/build-favicons.ts
 *
 * Outputs:
 *   public/icon-auto.svg     both marks in one file, switched by
 *                            prefers-color-scheme — the pre-hydration default
 *   public/favicon.ico       16/32/48 tombstone, for browsers that ignore SVG
 *                            icons and for the bare /favicon.ico request
 *   public/apple-touch-icon.png  180px tombstone
 */
import { readFile, writeFile } from "node:fs/promises";
import sharp from "sharp";

const PUB = new URL("../public/", import.meta.url).pathname;

// Everything between the outer <svg> tags, so the two marks can be composed
// into one file without duplicating their paths.
async function innerSvg(file: string) {
  const src = await readFile(PUB + file, "utf8");
  const open = src.indexOf(">", src.indexOf("<svg"));
  return src.slice(open + 1, src.lastIndexOf("</svg>")).trim();
}

// A .ico is a tiny container around whole PNG files: 6-byte header, one 16-byte
// directory entry per image, then the payloads. Writing it by hand avoids an
// ImageMagick dependency.
function buildIco(pngs: { size: number; data: Buffer }[]) {
  const header = Buffer.alloc(6 + 16 * pngs.length);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(pngs.length, 4);

  let offset = header.length;
  pngs.forEach(({ size, data }, i) => {
    const e = 6 + 16 * i;
    header.writeUInt8(size >= 256 ? 0 : size, e); // 0 means 256
    header.writeUInt8(size >= 256 ? 0 : size, e + 1);
    header.writeUInt8(0, e + 2); // palette size (0 = truecolor)
    header.writeUInt8(0, e + 3); // reserved
    header.writeUInt16LE(1, e + 4); // color planes
    header.writeUInt16LE(32, e + 6); // bits per pixel
    header.writeUInt32LE(data.length, e + 8);
    header.writeUInt32LE(offset, e + 12);
    offset += data.length;
  });

  return Buffer.concat([header, ...pngs.map((p) => p.data)]);
}

const [gy, wp] = await Promise.all([innerSvg("icon-gy.svg"), innerSvg("icon-wp.svg")]);

// Light is the base state and dark is the media-query override, matching
// lib/theme.tsx (dark → graveyard, light → WordPress).
await writeFile(
  PUB + "icon-auto.svg",
  `<!--
  GENERATED by scripts/build-favicons.ts — edit icon-gy.svg / icon-wp.svg instead.

  The pre-hydration favicon: both marks in one file, picked by the OS color
  scheme. components/FaviconSwitcher.tsx swaps in the single-skin file once the
  visitor's explicit theme choice is known.
-->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <style>
    .skin-gy { display: none }
    @media (prefers-color-scheme: dark) {
      .skin-wp { display: none }
      .skin-gy { display: inline }
    }
  </style>
  <g class="skin-wp">
${wp
  .split("\n")
  .map((l: string) => "    " + l)
  .join("\n")}
  </g>
  <g class="skin-gy">
${gy
  .split("\n")
  .map((l: string) => "    " + l)
  .join("\n")}
  </g>
</svg>
`,
);

// density high enough that the 180px raster is sampled from a crisp render
const render = (size: number) =>
  sharp(PUB + "icon-gy.svg", { density: 900 })
    .resize(size, size)
    .png()
    .toBuffer();

const [ico16, ico32, ico48, apple] = await Promise.all([
  render(16),
  render(32),
  render(48),
  render(180),
]);

await writeFile(
  PUB + "favicon.ico",
  buildIco([
    { size: 16, data: ico16 },
    { size: 32, data: ico32 },
    { size: 48, data: ico48 },
  ]),
);
await writeFile(PUB + "apple-touch-icon.png", apple);

console.log("wrote icon-auto.svg, favicon.ico, apple-touch-icon.png");
